name: Test Suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Unit Tests
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run unit tests
      run: npm test -- --verbose
      
    - name: Generate test results JSON
      run: npm test -- --json --outputFile=test-results.json
      if: always()
      
    - name: Upload test results artifact
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test-results.json
        retention-days: 30
      if: always()
      
    - name: Test coverage report
      run: npm test -- --coverage --coverageReporters=text
      if: always()